### ISSUE TITLE
Search results and ads parsing not working

### ISSUE THREAD

**Issue by pankajjha** [Monibrand/google-html-parser#5]
Hi There,

First of all really thanks for all the efforts you have made into this package, really appreciate it.

I am facing some issues with the package lately, sometimes it only parses the shopping ads, some times only single adword ads, but most importantly it is not parsing any results in the json.
I searched multiple keywords like iphone, alibaba, shein, anntaylor
None of them got search results in the JSON.
[https://share.getcloudapp.com/KouBp5Z4](https://share.getcloudapp.com/KouBp5Z4)
[https://share.getcloudapp.com/xQuDymdP](https://share.getcloudapp.com/xQuDymdP)
[https://share.getcloudapp.com/5zuXQkWo](https://share.getcloudapp.com/5zuXQkWo)

Also, can you tell me where can I start to fixing up the parser, because google is likely to change its results page at some intervals, some pointers to fix the parser and keep it up to date will be great.

**Comment by HugoPoi** [comment]
In the `test/mocks` folder we have sample test pages, if you can provide the google html page causing the parsing issue.
You can follow the guide in [CONTRIBUTING.md](https://github.com/Monibrand/google-html-parser/blob/master/CONTRIBUTING.md) if you want to help with a PR :smiley: 
Or if you have the keywords and user agent you are using for capturing, so i can reproduce.

**Comment by pankajjha** [comment]
[carloan.txt](https://github.com/Monibrand/google-html-parser/files/4964586/carloan.txt)

Here's an example
Keyword - car loan
Country - US
uule - W+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM
location - Austin, Texas, United States
Useragent - Unknown (as I am using some proxy crawlers to load SERP results and save it)

**Comment by HugoPoi** [comment]
I successfully reproduce the issue on our production setup, I will fix it today, google introduce a new template for organic results

**Comment by HugoPoi** [comment]
Publish the fix under `v0.3.0` on npm
